version: "3"

services:
    chloe:
        container_name: "chloe_bot"
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../:/app/
        working_dir: /app
        network_mode: "host"
        command:
            -   "aerich upgrade"
        entrypoint: [ "python", "main.py" ]
